### ISSUE TITLE
Hope to update to the latest version

### ISSUE THREAD

**Issue by leetan2021** [hoangjunior/AN515-54-51X1-Hackintosh#2]
open core 0.6.8

**Comment by h63one** [comment]
what new in oc 0.6.8 ? kinda lazy , when i have time i will update

**Comment by leetan2021** [comment]
Version 0.6.8 is ready to use themes in the boot interface

**Comment by leetan2021** [comment]
And now it is very difficult for EFI version to switch WiFi network. It needs to restart WiFi every time.I don't know if the new version can't be fixed

**Comment by h63one** [comment]
i will check it , no promise tho , i thought i was update this to 0.6.6 but guess im not , have fixed in 0.6.6 but i was forget to upload

**Comment by Raspytooth28** [comment]
I’ve updated to Opencore 0.6.8 and the latest kexts, if you want I can send my EFI.

**Comment by leetan2021** [comment]
> I’ve updated to Opencore 0.6.8 and the latest kexts, if you want I can send my EFI.

Thank you very much. I hope you can share your EFI with me and send it to my email.
leetan2021@163.com
